# Generated by Django 4.0.2 on 2023-05-16 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.CharField(blank=True, max_length=50, null=True)),
                ('operation_type', models.CharField(max_length=50)),
                ('operation_summary', models.CharField(max_length=100)),
                ('full_description', models.CharField(max_length=500)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'system_log',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_photo', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sur_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_email', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_email', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('entered_by', models.CharField(blank=True, max_length=50, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_group',
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_setting_entered_by', to='JailuApp.useraccount')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_setting_modified_by', to='JailuApp.useraccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_setting_user', to='JailuApp.useraccount')),
            ],
            options={
                'db_table': 'user_setting',
            },
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='JailuApp.usergroup'),
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lab_id_counter', models.IntegerField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_setting_entered_by', to='JailuApp.useraccount')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_setting_modified_by', to='JailuApp.useraccount')),
            ],
            options={
                'db_table': 'system_setting',
            },
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=200)),
                ('add', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('edit', models.BooleanField(default=False)),
                ('list', models.BooleanField(default=False)),
                ('view', models.BooleanField(default=False)),
                ('user_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='JailuApp.usergroup')),
            ],
            options={
                'db_table': 'group_permission',
            },
        ),
    ]
