# Generated by Django 4.0.2 on 2023-05-16 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JailuApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionForm',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('consent', models.CharField(max_length=20)),
                ('rate_nft_services', models.TextField(blank=True, null=True)),
                ('why_rate_nft_services', models.TextField(blank=True, null=True)),
                ('rate_nft_recommendation', models.IntegerField(blank=True, null=True)),
                ('why_rate_nft_recommendation', models.TextField(blank=True, null=True)),
                ('improve_nft_experience', models.TextField(blank=True, null=True)),
                ('any_comments', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='satisfaction_form_agent', to='JailuApp.useraccount')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='satisfaction_form_entered_by', to='JailuApp.useraccount')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='satisfaction_form_modified_by', to='JailuApp.useraccount')),
            ],
            options={
                'db_table': 'satisfaction_form',
            },
        ),
    ]
